name: chainoftrust
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_labeled_navigation_bar: ^2.0.2
  flutter_bloc: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  go_router: ^13.2.0

flutter:
  fonts:
    - family: OrelegaOne
      fonts:
        - asset: fonts/OrelegaOne-Regular.ttf

  uses-material-design: true
  assets:
    - assets/
